float:
  any:
  - base_args: ['@metric']
    constructor: PGVectoRS
    disabled: false
    docker_tag: ann-benchmarks-pgvecto-rs
    module: ann_benchmarks.algorithms.pgvecto-rs
    name: pgvecto-rs
    run_groups:
      pgvecto_rs:
        args: [[4, 20, 100]]
        query_args: [[10, 20, 40, 80, 120, 200, 400, 600, 800]]
