float:
  any:
  - base_args: ['@metric']
    constructor: PGLantern
    disabled: false
    docker_tag: ann-benchmarks-lantern-hnsw
    module: ann_benchmarks.algorithms.lantern-hnsw
    name: lantern-hnsw
    run_groups:
      lantern_hnsw:
        args: [[4, 20, 100]]
        query_args: [[10, 20, 40, 80, 120, 200, 400, 600, 800]]
